---
# tasks file for /Users/carlosfrias/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-setup-target-links

- name: Create the apigee folder, no links
  file:
    path: "{{ item.src }}"
    state: directory
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"
  with_items: "{{ target_links }}"
  when: target_links is defined

- name: Clean up any remaining link targets
  file:
    path: "{{ item.dest }}"
    state: absent
  with_items: "{{ target_links }}"
  when: target_links is defined

- name: Create the apigee folder, with links
  file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"
  with_items: "{{ target_links }}"
  when: target_links is defined
